
services:
  mongo:
    image: mongo:latest

    restart: always
    environment:
      MONGO_INITDB_DATABASE: plataforma
      # MONGO_INITDB_ROOT_USERNAME: root
      # MONGO_INITDB_ROOT_PASSWORD: example
      # ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    ports:
      - 27017:27017
    extra_hosts:
      - "host.docker.internal:host-gateway"    
    command: ["--bind_ip_all", "--port", "27017"]

  python-app:
    container_name: python-app
    build:
      context: ./python
      dockerfile: ./Dockerfile
    command: sh -c "sleep 5s"
    depends_on:
      - mongo
    ports:
      - 8888:8888
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
